name: auto-assign

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: PR作成者をアサイニーに設定
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr edit "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --add-assignee "${{ github.event.pull_request.user.login }}"
